/***********************************************************************/
/*                                                                     */
/*  FILE        :counter.c                                             */
/*  DATE        :Thu, Mar 22, 2012                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX210                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.53).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
                  



#include	"iodefine.h"
#include	<machine.h>                  
#include	"mu500-rx.h"


//#include "typedefine.h"
#ifdef __cplusplus
//#include <ios>                        // Remove the comment when you use ios
//_SINT ios_base::Init::init_cnt;       // Remove the comment when you use ios
#endif

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif




/* FPGA(CYCLONE)接続ピン配列に変換 */
#define	CNT_IN					CYCLONE_A_OUT		/* FPGAカウンタ 使用せず*/


#define	LED_D3					CYCLONE_A1			/* LED 0*/
#define	LED_D4					CYCLONE_A2			/* LED 1*/
#define	LED_D5					CYCLONE_A3			/* LED 2*/
#define	LED_D6					CYCLONE_A4			/* LED 3*/
#define	PLS_CLEAR				CYCLONE_A5			/* クリアパルス  */
#define	PLS_INCREMENT			CYCLONE_A6			/* 増加パルス  */
#define	PLS_DECREMENT			CYCLONE_A7			/* 減少パルス  */
#define	SW_START_STOP			CYCLONE_B0			/* スイッチ 0 */
#define	SW_RESET				CYCLONE_B1			/* スイッチ 1 */
#define	SW_INCREMENT			CYCLONE_B2			/* スイッチ 2 */
#define	SW_DECREMENT			CYCLONE_B3			/* スイッチ 3 */


#define	DETECT_1MS				(5-1)				/* １msタイマカウント回数（1ms÷0.2ms）*/

#define	DETECT_1SEC				(1000-1)			/* １秒タイマカウント回数（1秒÷1ms） */


/*チャタリング一致回数*/
#define	N_START_STOP			5
#define	N_RESET					5
#define	N_INCREMENT				5
#define	N_DECREMENT				5

#define	SW_ACT					0					/* PUSH-SW状態 */

#define	N_FPGACNT				5					/*FPGAからの指示パルス 使用せず*/



/*チャタリング周期（ms単位）*/
#define	MS_START_STOP			5
#define	MS_RESET				5					/*10->5*/
#define	MS_INCREMENT			5					/*10->5*/
#define	MS_DECREMENT			5					/*10->5*/
#define	MS_CNTIN				900					/* 使用せず */



#define	N_FPGADECREQ			5					/*FPGAからの指示パルス回数 使用せず*/
#define	N_FPGADECANS			5					/*FPGAからの指示パルスでDECを返す回数 使用せず*/

#define	EVENT_PUSH_START_STOP	0					/*スタート/ストップ押下イベント*/
#define	EVENT_PUSH_RESET		1					/*リセット押下イベント*/
#define	EVENT_PUSH_INCREMENT	2					/*インクリメントイベント*/
#define	EVENT_PUSH_DECREMENT	3					/*デクリメントイベント*/
#define	NO_EVENT				4					/*イベントなし*/
#define	EVENT_NUM				5					/*イベントの数*/



/*キー種別*/
enum keyid	{
	KEY_START_STOP,									/* 開始／停止 	0 */
	KEY_RESET,										/* クリア     	1 */
	KEY_INCREMENT,									/* 増加       	2 */
	KEY_DECREMENT,									/* 減少       	3 */
	KEY_CNTIN,										/* FPGA信号	未使用 	4 */
	KEY_INIT,										/* 初期状態   	5 */
	KEY_DB,											/* デバッグ１ 	6 */
	KEY_DB2											/* デバッグ２ 	7 */
};
/*タイマ状態*/
enum timerid	{
	STATE_STOP,										/* 停止中 */
	STATE_START,									/* 開始中 */
	STATE_NUM										/*状態の数*/		
};


//=============================================================================
// グローバル変数
//=============================================================================
volatile int			state = STATE_STOP;			/* タイマ状態 */
volatile unsigned short	time_count_1ms = 0;			/* 1msタイマカウント */
volatile unsigned short	time_count_1sec = 0;		/* 1秒タイマカウント */
volatile unsigned short	timeup_1ms = 0;				/* 1msタイムアップフラグ */
volatile unsigned char	timeup_1sec = 0;			/* 1secタイムアップフラグ */

volatile unsigned short	time_count_fpga = 0;		/* fpgaからの指示のタイムアップフラグ 使用せず*/

volatile unsigned short	dec_count_fpga = 0;			/* fpgaからの指示でDECを返す期間フラグ */
volatile unsigned short	send_count_fpga = 0;		/* fpgaからの指示でDECを返す回数 */


volatile struct	{
	unsigned char	onoff;							/* 各キーの入力値 */
	unsigned char	count;							/* 残り一致回数 */
	unsigned short	time;							/* 残り周期   */
}	key[5] =											
{
	{ SW_ACT, N_START_STOP, MS_START_STOP },					
	{ SW_ACT, N_RESET     , MS_RESET      },					
	{ SW_ACT, N_INCREMENT , MS_INCREMENT  },					
	{ SW_ACT, N_DECREMENT , MS_DECREMENT  },					
	{ SW_ACT, N_FPGACNT	  , MS_CNTIN	  }			/* 使用せず*/
};


int count_50s = 0;								    /* 50秒カウント用 */


//=============================================================================
// 関数プロトタイプ
//=============================================================================
void	initial(void);									/* 初期化処理 */
void	initial_port(void);								/* 入出力ピン初期化処理 */
void	timer_start(void);								/* タイマ開始処理（１秒タイマ用） */
void	timer_stop(void);								/* タイマ停止処理（１秒タイマ用） */
void	timer_count_1sec(void);							/* １秒タイマカウントアップ処理 */
void	out_pulse(int type);							/* HIGHパルス出力処理 */
void	out_led_pattern(int type);						/* LEDパターン出力処理 */
void	push_start(void);							    /* スタート押下処理 */
void	push_stop(void);							    /* ストップ押下処理 */
void	push_reset(void);								/* リセット押下処理 */
void	push_increment(void);							/* インクリメント押下処理 */
void	push_decrement(void);							/* デクリメント押下処理 */
void	nopt(void);										/* 何もしない   */
int     get_eve(void);									/* イベント取得 */
void    go_on_time(void);                               /* 時間経過時の処理*/
void    go_on_1sec(void);                               /* 1s経過の処理 */
void	decrement_5sec(void);
void    judge_decrement(void);							/* 50秒経過するとデクリメントを行う */

//void	INT_TMR0(void);


void	initTMR(void);									/* タイマ設定 */
void	INT_CMT0(void);									/* タイマ割込み処理 */



/* チャタリング除去処理 */
int		chattering(int key_id, volatile unsigned char current_key, unsigned char n, unsigned char time);

void	initial_param(void);							/*内部データ初期化*/

//=============================================================================
// 状態遷移テーブル
//=============================================================================
enum timerid  nowstate;  
typedef struct{
	void  			(*action)(void);					/*アクション*/
	enum  timerid	nextstate;							/*次の状態*/
}StateShift;
	
	
const static StateShift		stateshift[EVENT_NUM][STATE_NUM] = {
		{{push_start    , STATE_START}  ,  {push_stop  		, STATE_STOP }},
		{{push_reset    , STATE_STOP }  ,  {push_reset 		, STATE_STOP }},
		{{push_increment, STATE_STOP }  ,  {nopt       		, STATE_START}},
		{{push_decrement, STATE_STOP }  ,  {nopt       		, STATE_START}},
		{{nopt          , STATE_STOP }  ,  {go_on_time      , STATE_START}}
};


		
//-----------------------------------------------------------------------------
//	Function Name    : main
//	Contents         : メイン処理
//	Parameter Value  : None
//	Return Value     : None
//	Date             : 2012-03-21
//-----------------------------------------------------------------------------
void main(void)
{
	
	
	int  event = NO_EVENT;						/*イベントの初期化*/
	initial();									/* 初期化 */


	initial_param();							/*内部データ初期化*/
	event = NO_EVENT;
	nowstate = STATE_STOP;						/*状態の初期化*/

	initTMR();									/* タイマ起動 */

	while( 1 )
	{
		
		/* 1ms毎の処理 */
		if( timeup_1ms != 0 )
		{	
			timeup_1ms = 0;								/*イベント取得*/
			
			event = get_eve();
			
			stateshift[event][nowstate].action();		/*アクション*/
			
			nowstate = stateshift[event][nowstate].nextstate; /*状態遷移*/
		}
		

	}
}

//-----------------------------------------------------------------------------
//	Function Name    : initial
//	Contents         : 初期化処理
//	Parameter Value  : None
//	Return Value     : None
//	Date             : 2012-03-21
//-----------------------------------------------------------------------------
void	initial(void)
{

	initial_port();										/* 入出力ピン初期化 */

	timer_stop();


	out_led_pattern(KEY_INIT);							/* ダウンロード完了確認用LED表示 */

}




//-----------------------------------------------------------------------------
//	Function Name    : initial_param
//	Contents         : 初期化処理
//	Parameter Value  : None
//	Return Value     : None
//	Date             : 2012-03-21
//-----------------------------------------------------------------------------
void	initial_param(void)
{

	key[KEY_START_STOP].onoff = SW_START_STOP; 
	key[KEY_START_STOP].count = N_START_STOP;
	key[KEY_START_STOP].time  = MS_START_STOP;

	key[KEY_RESET].onoff = SW_RESET; 
	key[KEY_RESET].count = N_RESET;
	key[KEY_RESET].time  = MS_RESET;

	key[KEY_INCREMENT].onoff = SW_INCREMENT; 
	key[KEY_INCREMENT].count = N_INCREMENT;
	key[KEY_INCREMENT].time  = MS_INCREMENT;

	key[KEY_DECREMENT].onoff = SW_DECREMENT; 
	key[KEY_DECREMENT].count = N_DECREMENT;
	key[KEY_DECREMENT].time  = MS_DECREMENT;




	dec_count_fpga = 0;
	send_count_fpga = 0;


}
//-----------------------------------------------------------------------------
//	Function Name    : get_eve
//	Contents         : イベントを取得する
//	Parameter Value  : None
//	Return Value     : None
//	Date             : 2012-03-21
//-----------------------------------------------------------------------------

int get_eve(void)
{
	int		rcd;

	volatile unsigned char c_key;

	while(1)
	{	
			/* スタート／ストップキー判定 */
			c_key = SW_START_STOP;
			rcd = chattering(KEY_START_STOP, c_key, N_START_STOP, MS_START_STOP);
			if( rcd != 0 && key[KEY_START_STOP].onoff == SW_ACT )
			{
				return EVENT_PUSH_START_STOP;
			}


			/* リセットキー判定 */
			c_key = SW_RESET;
			rcd = chattering(KEY_RESET, c_key, N_RESET, MS_RESET);
			if( rcd != 0 && key[KEY_RESET].onoff == SW_ACT )	
			{
				return EVENT_PUSH_RESET;
			}

			/* インクリメントキー判定 */
			c_key = SW_INCREMENT;
			rcd = chattering(KEY_INCREMENT, c_key, N_INCREMENT, MS_INCREMENT);
			if( rcd != 0 && key[KEY_INCREMENT].onoff == SW_ACT )
			{
				return EVENT_PUSH_INCREMENT;
			}

			/* デクリメントキー判定 */
			c_key = SW_DECREMENT;
			rcd = chattering(KEY_DECREMENT, c_key, N_DECREMENT, MS_DECREMENT);
			if( rcd != 0 && key[KEY_DECREMENT].onoff == SW_ACT )
			{
				return EVENT_PUSH_DECREMENT;
			}
			
			return NO_EVENT;
	}
}


//-----------------------------------------------------------------------------
//	Function Name    : judge_decrement
//	Contents         : 50秒経過したかどうか判断する。
//	Parameter Value  : None   
//	Return Value     : None
//	Date             : 2012-03-21
//----------------------------------------------------------------------------
void judge_decrement(void)
{
	
	if(count_50s >= 50)
	{
		dec_count_fpga = 1;							/*指示回数オーバー*/
	
	}

}

//-----------------------------------------------------------------------------
//	Function Name    : decrement_5sec
//	Contents         : 50秒経過したかの判断を元に５秒デクリメントを行う
//	Parameter Value  : None   
//	Return Value     : None
//	Date             : 2012-03-21
//----------------------------------------------------------------------------
void decrement_5sec(void)
{
		push_decrement();								/*DECをFPGAへ送信*/
		send_count_fpga++;

		if (send_count_fpga >= N_FPGADECANS) 			/*DEC回数をN_FPGADEC送信したら*/
		{
				dec_count_fpga = 0;
				send_count_fpga = 0;
				count_50s = 0;
		}
		timer_start();

}

//-----------------------------------------------------------------------------
//	Function Name    : go_on_1sec
//	Contents         : 1秒経過毎にインクリメントを行う。
//	Parameter Value  : None   
//	Return Value     : None
//	Date             : 2012-03-21
//----------------------------------------------------------------------------
void go_on_1sec(void)
{
		out_pulse(KEY_INCREMENT);							/* 増加パルス送信 */
		out_led_pattern(KEY_START_STOP);					/* LEDパターン表示 */
		out_led_pattern(KEY_INCREMENT);						/* デバッグ用LED表示 */
}

//-----------------------------------------------------------------------------
//	Function Name    : go_on_time
//	Contents         : 時間経過時の処理
//	Parameter Value  : None   
//	Return Value     : None
//	Date             : 2012-03-21
//----------------------------------------------------------------------------
void   go_on_time(void)
{		
	/* 1秒毎の処理 */
	if( timeup_1sec != 0 )
	{                     
		timeup_1sec = 0;
		out_led_pattern(KEY_START_STOP);			/* LEDパターン表示 */


		go_on_1sec();								/* 1秒経過毎にインクリメントを行う*/
		count_50s++;

	}
}

//-----------------------------------------------------------------------------
//	Function Name    : push_start
//	Contents         : スタート押下処理
//	Parameter Value  : None
//	Return Value     : None
//	Date             : 2012-03-21
//-----------------------------------------------------------------------------
void	push_start(void)
{
		timer_start();
		count_50s = 0;
		initial_param();								    /* 内部データ初期化*/

		out_led_pattern(KEY_START_STOP);					/* LEDパターン表示 */
}


//-----------------------------------------------------------------------------
//	Function Name    : push_stop
//	Contents         : スタート押下処理
//	Parameter Value  : None
//	Return Value     : None
//	Date             : 2012-03-21
//-----------------------------------------------------------------------------
void	push_stop(void)
{
		timer_stop();
	
		out_led_pattern(KEY_START_STOP);					/* LEDパターン表示 */
}

//-----------------------------------------------------------------------------
//	Function Name    : push_reset
//	Contents         : リセット押下処理
//	Parameter Value  : None
//	Return Value     : None
//	Date             : 2012-03-21
//-----------------------------------------------------------------------------
void	push_reset(void)
{
		out_pulse(KEY_RESET);								/* クリアパルス送信 */

		out_led_pattern(KEY_RESET);							/* LEDパターン表示 */
}

//-----------------------------------------------------------------------------
//	Function Name    : push_increment
//	Contents         : インクリメント押下処理
//	Parameter Value  : None
//	Return Value     : None
//	Date             : 2012-03-21
//-----------------------------------------------------------------------------
void	push_increment(void)
{
		out_pulse(KEY_INCREMENT);							/* 増加パルス送信 */
		out_led_pattern(KEY_INCREMENT);						/* LEDパターン表示 */
}

//-----------------------------------------------------------------------------
//	Function Name    : push_decrement
//	Contents         : デクリメント押下処理
//	Parameter Value  : None
//	Return Value     : None
//	Date             : 2012-03-21
//-----------------------------------------------------------------------------
void	push_decrement(void)
{
		out_pulse(KEY_DECREMENT);							/* 減少パルス送信 */
		out_led_pattern(KEY_DECREMENT);						/* LEDパターン表示 */
}

//-----------------------------------------------------------------------------
//	Function Name    : nopt
//	Contents         : 何もしない処理
//	Parameter Value  : None
//	Return Value     : None
//	Date             : 2012-03-21
//-----------------------------------------------------------------------------
void  nopt(void)
{
	;
}


//-----------------------------------------------------------------------------
//	Function Name    : out_pulse
//	Contents         : HIGHパルス出力処理
//	Parameter Value  : type    : 出力するパルスの種類
//	                 :               KEY_RESET     : クリア
//	                 :               KEY_INCREMENT : 増加
//	                 :               KEY_DECREMENT : 減少
//	Return Value     : None
//	Date             : 2012-03-21
//-----------------------------------------------------------------------------
void	out_pulse(int type)
{
	
	switch( type )
	{
		case	KEY_RESET:									/* クリア */
				PLS_CLEAR = 1;
				PLS_CLEAR = 0;	
				break;

		case	KEY_INCREMENT:								/* 増加 */
				PLS_INCREMENT = 1;
				PLS_INCREMENT = 0;
				break;

		case	KEY_DECREMENT:								/* 減少 */
				PLS_DECREMENT = 1;
				PLS_DECREMENT = 0;
				break;

		default:
				break;
	}
}

//-----------------------------------------------------------------------------
//	Function Name    : out_led_pattern
//	Contents         : LEDパターン出力処理
//	Parameter Value  : type    : 出力するパルスの種類
//	                 :               KEY_RESET     : クリア
//	                 :               KEY_INCREMENT : 増加
//	                 :               KEY_DECREMENT : 減少
//	Return Value     : None
//	Date             : 2012-03-21
//-----------------------------------------------------------------------------
void	out_led_pattern(int type)
{
	
	switch( type )
	{

		case	KEY_RESET:									/* クリア */
			LED_D3 = 1;
			LED_D4 = 0;
			LED_D5 = 0;
			LED_D6 = 0;
			break;

		case	KEY_START_STOP:								/* 開始／停止 */
			LED_D3 = 0;
			LED_D4 = 1;
			LED_D5 = 0;
			LED_D6 = 0;
			break;

		case	KEY_INCREMENT:								/* 増加 */
			LED_D3 = 0;
			LED_D4 = 0;
			LED_D5 = 1;
			LED_D6 = 0;
			break;

		case	KEY_DECREMENT:								/* 減少 */
			LED_D3 = 0;
			LED_D4 = 0;
			LED_D5 = 0;
			LED_D6 = 1;
			break;

		case	KEY_INIT:									/* 初期化 */
			LED_D3  = 0;
			LED_D4  = 1;
			LED_D5 = 1;
			LED_D6 = 0;
			break;

		case	KEY_DB:										/* デバッグ */
			LED_D3 = 0;
			LED_D4 = 1;
			LED_D5 = 0;
			LED_D6 = 1;
			break;

		case	KEY_DB2:									/* デバッグ */
			LED_D3 = 1;
			LED_D4 = 0;
			LED_D5 = 0;
			LED_D6 = 1;
			break;

		default:
			LED_D3 = 0;
			LED_D4 = 0;
			LED_D5 = 0;
			LED_D6 = 0;
			break;
	}

}

//-----------------------------------------------------------------------------
//	Function Name    : chattering
//	Contents         : チャタリング除去処理
//	Parameter Value  : key_id      : キー種類
//	                 :               KEY_START_STOP: 開始／停止
//	                 :               KEY_RESET     : クリア
//	                 :               KEY_INCREMENT : 増加
//	                 :               KEY_DECREMENT : 減少
//	                 : current_key : 現在のキー値
//	                 : n           : 一致回数
//	                 : time        : 周期
//	Return Value     : 変化有無
//	                 :   0 : 変化なし、 以外 : 変化あり
//	Date             : 2012-03-21
//-----------------------------------------------------------------------------
int		chattering(int key_id, volatile unsigned char current_key, unsigned char n, unsigned char time)
{
	int		ret = 0;

	/* 測定周期になるまで待つ */
	if( key[key_id].time > 1 )
	{
		key[key_id].time--;
		return( ret );
	}
	key[key_id].time = time;

	/* ｎ回一致でキー値を確定する */
	if( key[key_id].onoff == current_key )
	{
		key[key_id].count = n - 1;
	}
	else
	{
		/* n回一致した場合は入力値を確定 */
		if( key[key_id].count <= 1 )
		{
			key[key_id].onoff = current_key;
			ret = 1;
		}
		else
		{
			key[key_id].count--;
		}
	}
	return( ret );
}



//-----------------------------------------------------------------------------
//	Function Name    : timer_start
//	Contents         : タイマ開始処理（１秒タイマ用）
//	Parameter Value  : None
//	Return Value     : None
//	Date             : 2012-03-21
//-----------------------------------------------------------------------------
void	timer_start(void)
{

	time_count_1sec = 0;

}

//-----------------------------------------------------------------------------
//	Function Name    : timer_stop
//	Contents         : タイマ停止処理（１秒タイマ用）
//	Parameter Value  : None
//	Return Value     : None
//	Date             : 2012-03-21
//-----------------------------------------------------------------------------
void	timer_stop(void)
{
	/*何もしない*/
}

//-----------------------------------------------------------------------------
//	Function Name    : timer_upcount_1sec
//	Contents         : １秒タイマカウントアップ処理
//	Parameter Value  : None
//	Return Value     : None
//	Date             : 2012-03-21
//-----------------------------------------------------------------------------
void	timer_count_1sec(void)
{
	/* タイマ停止中は何もしない */
	if( nowstate == STATE_STOP )
	{
		return;
	}
	/* 1秒待ち */
	if( time_count_1sec < DETECT_1SEC )
	{
		time_count_1sec++;
		return;
	}
	time_count_1sec = 0;
	timeup_1sec = 1;
}




//=============================================================================
//        割込み処理
//=============================================================================
//-----------------------------------------------------------------------------
//	Function Name    : Excep_TMR0_CMI0A
//	Contents         : オーバーフロー割込み処理
//	                 : タイマ開始中0.2msごとに割込みが発生する。
//	Parameter Value  : None
//	Return Value     : None
//	Date             : 2012-03-21
//-----------------------------------------------------------------------------
//
// TMR0_CMIA0(チャネル0 コンペアマッチA)割り込み
//
#pragma interrupt (Excep_TMR0_CMI0A(vect=174))	// 割り込み関数宣言,ベクタ登録
void Excep_TMR0_CMI0(void)
//void INT_TMR0(void)
{

		/* 1ms待ち */
		if( time_count_1ms < DETECT_1MS )
		{
			time_count_1ms++;
			return;
		}

		time_count_1ms = 0;
		timeup_1ms = 1;

		timer_count_1sec();								/* １秒タイマカウントアップ */

}




void INT_CMT0(void)
{


//	PORTB.PODR.BIT.B0 = 1;			/* DEBUG */
//	PORTH.PODR.BIT.B0 = 1;			/* DEBUG */

	/* 1ms待ち */
	if( time_count_1ms < DETECT_1MS )
	{
		time_count_1ms++;
	}

	else
	{
		time_count_1ms = 0;
		timeup_1ms = 1;

		timer_count_1sec();					/* １秒タイマカウントアップ */
	}

//	PORTB.PODR.BIT.B0 = 0;			/* DEBUG */
//	PORTH.PODR.BIT.B0 = 0;			/* DEBUG */


}





//-----------------------------------------------------------------------------
//	Function Name    : initTMR
//    8ビットタイマ(TMR)初期設定
//   16ビットカウントモード,コンペアマッチA割り込み許可、500msインターバル
//
//	Parameter Value  : None
//	Return Value     : None
//	Date             : 2012-03-21
//-----------------------------------------------------------------------------
void initTMR(void)
{

	SYSTEM.PRCR.WORD = 0xA502;				//MSTPCRAレジスタプロテクトの解除
	SYSTEM.MSTPCRA.LONG = 0x67ff7fdf;		//モジュールストップコントロールレジスタA タイマ起動
	SYSTEM.PRCR.WORD = 0xA500;				//レジスタプロテクト

	CMT0.CMCR.BIT.CKS = 0;					//クロック選択　PCLK/8

	CMT0.CMCNT = 0;							//コンペアマッチタイマカウンタ値（初期値=0のまま）

// 内部クロック設定
	CMT0.CMCOR = (800 -1);					//この値が、CMCNTのカウントアップ値と一致すると割込みが入る


	CMT0.CMCR.BIT.CMIE = 1;					//コンペアマッチ割込み許可
	CMT.CMSTR0.BIT.STR0 = 1;				//カウント動作開始

	IPR(CMT0,CMI0) = 15;					//割込み優先度
	IEN(CMT0,CMI0) = 1;						//割込み解除


// 内部クロック選択の場合
	// 中速動作モードＡ（デフォルト）= PCLK:32MHz
	// 0.2ms設定し、5回割込み発生で1msとする
	// 設定値＝時間×動作周波数÷分周
	//       ＝0.2ms×32MHz÷8
	//       ＝(0.2÷1000)(sec)×(32×1000×1000)(Hz)÷8
	//       ＝800


}

//-----------------------------------------------------------------------------
//	Function Name    : initial_port
//	Contents         : 入出力ピン初期化処理
//	Parameter Value  : None
//	Return Value     : None
//	Date             : 2012-03-21
//-----------------------------------------------------------------------------
void	initial_port(void)
{

	int i;

	SYSTEM.PRCR.WORD = 0xA501;				//MOSCCR.MOSTPレジスタプロテクトの解除
	SYSTEM.MOSCCR.BIT.MOSTP = 0;			//メインクロック起動 
	SYSTEM.PRCR.WORD = 0xA500;				//レジスタプロテクト

//  デフォルト65536サイクルのままで使用
//	SYSTEM.PRCR.WORD = 0xA502;				//MOSCWTCRレジスタプロテクトの解除
//	SYSTEM.MOSCWTCR.BIT.MSTS = 0x0b;		//クロック安定待ちカウンタ 32768サイクル
//	SYSTEM.PRCR.WORD = 0xA500;				//MOSCWTCRレジスタプロテクト

	for(i=0;i<1024;i++)
	{
			//クロック安定待ち
	}


	SYSTEM.PRCR.WORD = 0xA504;				//080200レジスタプロテクトの解除
	*(volatile unsigned char *)0x00080200 = 0x00;
	SYSTEM.PRCR.WORD = 0xA500;				//080200レジスタプロテクト

	SYSTEM.PRCR.WORD = 0xA501;				//SCKCRレジスタプロテクトの解除
	SYSTEM.SCKCR3.BIT.CKSEL = 1;			//メイン発振を選択
											// OPCCR.OPCM[2:0]は初期値のままなので
											// メイン発振は中速動作モードＡ32MHzで動く
	SYSTEM.PRCR.WORD = 0xA500;				//SCKCRレジスタプロテクト


// 入出力設定
	POTR5_MODE = 0x00;				/*PORT0を入力（初期値）*/
	POTRE_MODE = 0xff;				/*PORTEを出力*/

	PORTB.PDR.BIT.B0 = 1;			/* B0方向レジスタ　DEBUG*/
	PORTH.PDR.BIT.B0 = 1;			/* B0方向レジスタ　DEBUG*/

}


#ifdef __cplusplus
void abort(void)
{

}
#endif

/*----------------------          End of File          ----------------------*/

